// This file is generated by scripts/sync-package-versions.mjs.
// Do not edit it manually.

export const packageVersions = {
  '@tiqlyne/motion-core': '0.1.1',
  '@tiqlyne/motion-web': '0.2.0',
  '@tiqlyne/motion-pack-basic': '0.2.0'
} as const;

export type TiqlynePackageName = keyof typeof packageVersions;

export const packageVersionRows: Array<{
  name: TiqlynePackageName;
  description: string;
}> = [
  {
    name: '@tiqlyne/motion-core',
    description: 'Platform-independent engine core'
  },
  {
    name: '@tiqlyne/motion-web',
    description: 'Browser driver using the Web Animations API'
  },
  {
    name: '@tiqlyne/motion-pack-basic',
    description: 'Official basic motion definitions'
  }
];

const uniqueVersions = Array.from(new Set(Object.values(packageVersions)));

export const packageVersionSummary =
  uniqueVersions.length === 1
    ? `All public packages are currently ${uniqueVersions[0]}`
    : 'Public packages use independent versions';
